title: "Juan Merizalde, PhD"
description: "Researcher in Militant and Sub-State Violence, Regional Focus: AFPAK"
baseurl: ""
url: "https://juanmerizalde.github.io"

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

author:
  name: "Juan Merizalde, PhD"
  bio: "Independent researcher focusing on militant and sub-state violence with a regional specialization in Afghanistan and Pakistan."
  location: "Global"
  avatar: "/assets/images/profile.jpg"

nav:
  - title: "About"
    url: /about/
  - title: "Publications"
    url: /publications/
  - title: "Datasets"
    url: /datasets/
  - title: "Teaching"
    url: /teaching/
  - title: "Blog"
    url: /blog/
  - title: "Contact"
    url: /contact/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
